version: '3.3'
services:
    database:
        image: postgres
        ports:
          - "5432:5432"
        restart: always
    server:
        env_file: .env
        build: .
        ports:
         - "5000:5000"
        depends_on:
          - database
        image: webprecon
        volumes:
          - .:/app
        command: ["app:app", "-b", "0.0.0.0:5000", "--reload"]
