version: '3.3'
services:
    database:
        env_file: database.env
        image: postgres
        ports:
          - "5432:5432"
        restart: always
    server:
        env_file: .env
        build: .
        ports:
         - "8000:8000"
        depends_on:
          - database
        image: wxbsite
        volumes:
          - .:/app
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
