version: '3.7'

services:
  database:
    env_file:
      - .env
    container_name: database
    image: postgres
  frontend:
    env_file:
      - .env
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: lovelace/frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
  backend:
    env_file:
      - .env
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: lovelace/backend
    volumes:
      - './backend:/app'
    ports:
      - '8000:8000'
    depends_on:
      - database
