version: '3.3'
services:
    database:
        env_file: database.env
        image: postgres
        ports:
          - "5432:5432"
        restart: always
    server:
        build: .
        ports:
         - "5000:5000"
        depends_on:
          - database
        image: camel
        volumes:
          - .:/server
        command: ["app:app", "-b", "0.0.0.0:5000", "--reload", "--worker-tmp-dir", "/dev/shm", "--workers", "2", "--threads", "4", "--worker-class", "gthread"]
