version: '3.3'
services:
    database:
        env_file: env/database.env
        image: postgres
        ports:
          - "5432:5432"
        restart: always
    server:
        env_file: env/development.env
        build: .
        ports:
         - "8000:8000"
        depends_on:
          - database
        image: selfcarto
        volumes:
          - .:/server
        command: ["selfcarto.wsgi:application", "-b", "0.0.0.0:8000", "--reload", "--worker-tmp-dir", "/dev/shm", "--workers", "2", "--threads", "4", "--worker-class", "gthread"]