# Generated by Django 2.2.2 on 2019-06-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0003_auto_20190606_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
