# Generated by Django 3.0.1 on 2020-01-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidefone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Lebron', max_length=100),
            preserve_default=False,
        ),
    ]
