# Generated by Django 3.0.1 on 2020-01-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
