# Generated by Django 3.0.1 on 2020-01-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0002_auto_20200122_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='summary',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('uploaded_at', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pxdcast.Podcast')),
            ],
            options={
                'db_table': 'pxdcast_episodes',
            },
        ),
    ]
