# Generated by Django 3.0.1 on 2020-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='uploaded_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='apple_podcasts_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('name', 'podcast')},
        ),
    ]
