# Generated by Django 3.0.1 on 2020-01-31 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0006_auto_20200124_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='last_episodes_query_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
