# Generated by Django 3.0.1 on 2020-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0007_podcast_last_episodes_query_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='last_episodes_query_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
