# Generated by Django 3.0.1 on 2020-01-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0008_auto_20200131_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='last_episodes_query_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
