# Generated by Django 3.0.1 on 2020-02-02 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pxdcast', '0013_auto_20200131_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='subscriptions',
            field=models.ManyToManyField(through='pxdcast.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
