# Generated by Django 3.0.1 on 2020-02-02 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pxdcast', '0014_podcast_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', through='pxdcast.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
