# Generated by Django 3.0.1 on 2020-02-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0016_auto_20200202_1245'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='episode',
            table='episodes',
        ),
        migrations.AlterModelTable(
            name='podcast',
            table='podcasts',
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscriptions',
        ),
    ]
