# Generated by Django 3.0.1 on 2020-02-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0020_auto_20200202_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='subscription',
        ),
    ]
