# Generated by Django 3.0.1 on 2020-02-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0021_remove_podcast_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
