# Generated by Django 3.0.1 on 2020-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200202_1251'),
        ('pxdcast', '0024_auto_20200202_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='subscription',
            field=models.ManyToManyField(related_name='subscribers', through='pxdcast.Subscription', to='accounts.Pxdcast'),
        ),
    ]
