# Generated by Django 3.0.1 on 2020-02-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0036_episode_podcast_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='last_episodes_query_at',
        ),
    ]
