# Generated by Django 3.0.1 on 2020-02-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0037_remove_podcast_last_episodes_query_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='uploaded_at',
            new_name='published_at',
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('name', 'published_at', 'duration', 'url', 'podcast')},
        ),
    ]
