workflows:
  version: 2
  build-deploy:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: pip install -r requirements/prod.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements/prod.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run: python manage.py test
      - store_test_results:
          path: claro-test-results
      - store_artifacts:
          path: claro-test-results
          destination: tr1