workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
      - run:
          name: Install python dependencies in a virtualenv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/development.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: 
          command: |
            sudo pip install awsebcli
      - save_cache:
          key: deps9-{{ .Branch }}-awsebcli
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
      - run:
          name: Deploy master to AWS via EB
          command: |
            eb deploy
      