workflows:
  version: 2
  build-deploy:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
            pipenv lock -r > requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run: pipenv run pytest
      - store_test_results:
          path: sidefone-test-results
      - store_artifacts:
          path: sidefone-test-results
          destination: tr1