# Generated by Django 3.0.1 on 2020-02-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0033_auto_20200204_2022'),
        ('accounts', '0008_pxdcast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pxdcast',
        ),
    ]
