# Generated by Django 3.0.1 on 2020-02-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200202_1251'),
        ('pxdcast', '0026_auto_20200202_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='subscribers',
            field=models.ManyToManyField(through='pxdcast.Subscription', to='accounts.Pxdcast'),
        ),
    ]
