# Generated by Django 3.0.1 on 2020-02-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0034_episode_podcast_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='account',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='podcast',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
