# Generated by Django 3.0.1 on 2020-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0003_auto_20200123_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
