# Generated by Django 3.0.1 on 2020-02-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxdcast', '0029_auto_20200202_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
