# Generated by Django 3.0.1 on 2020-02-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200202_1251'),
        ('pxdcast', '0025_podcast_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='subscription',
            new_name='subscribers',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.Pxdcast'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='pxdcast.Podcast'),
        ),
    ]
