"""empty message

Revision ID: 16635d5168c3
Revises: 900314545d7e
Create Date: 2019-06-28 13:07:03.688605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16635d5168c3'
down_revision = '900314545d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'user_id')
    # ### end Alembic commands ###
