"""empty message

Revision ID: 1d9f82c8c2b7
Revises: 493b340439dc
Create Date: 2019-07-16 18:59:13.203547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d9f82c8c2b7'
down_revision = '493b340439dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('menus_account_id_fkey', 'menus', type_='foreignkey')
    op.drop_constraint('products_account_id_fkey', 'products', type_='foreignkey')
    op.drop_table('accounts')
    op.add_column('menus', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menus', 'merchant', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('menus', 'account_id')
    op.add_column('products', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'merchant', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_account_id_fkey', 'products', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'merchant_id')
    op.add_column('menus', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.create_foreign_key('menus_account_id_fkey', 'menus', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('menus', 'merchant_id')
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='accounts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='accounts_pkey')
    )
    op.drop_table('merchant')
    # ### end Alembic commands ###
