"""empty message

Revision ID: 2119b66b28ee
Revises: f0a409fc8596
Create Date: 2019-07-04 23:56:58.893791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2119b66b28ee'
down_revision = 'f0a409fc8596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventories_when_sold_id_fkey', 'inventories', type_='foreignkey')
    op.drop_constraint('inventories_product_id_fkey', 'inventories', type_='foreignkey')
    op.create_foreign_key(None, 'inventories', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inventories', 'inventories_when_sold', ['when_sold_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_account_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_etsy_product_id_fkey', 'products_etsy', type_='foreignkey')
    op.create_foreign_key(None, 'products_etsy', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_etsy', type_='foreignkey')
    op.create_foreign_key('products_etsy_product_id_fkey', 'products_etsy', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_account_id_fkey', 'products', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.create_foreign_key('inventories_product_id_fkey', 'inventories', 'products', ['product_id'], ['id'])
    op.create_foreign_key('inventories_when_sold_id_fkey', 'inventories', 'inventories_when_sold', ['when_sold_id'], ['id'])
    # ### end Alembic commands ###
