"""empty message

Revision ID: 21949151629c
Revises: 2f45511419cd
Create Date: 2019-07-04 14:11:08.916665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21949151629c'
down_revision = '2f45511419cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('caption', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('url', sa.String(length=255), nullable=True))
    op.drop_column('products_etsy', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_etsy', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('products', 'url')
    op.drop_column('products', 'title')
    op.drop_column('products', 'description')
    op.drop_column('products', 'caption')
    # ### end Alembic commands ###
