"""empty message

Revision ID: 255ae5521a78
Revises: dfe3b83c26b0
Create Date: 2019-07-03 19:47:43.640794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255ae5521a78'
down_revision = 'dfe3b83c26b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'user_id')
    op.drop_column('channels', 'secret')
    op.drop_column('channels', 'shop_id')
    op.drop_column('channels', 'slug')
    op.drop_column('channels', 'token')
    op.drop_column('channels', 'shop_name')
    op.add_column('listings', sa.Column('id', sa.Integer(), nullable=False, autoincrement=True, primary_key=True))
    op.drop_column('listings', 'channel_id')
    op.drop_column('listings', 'inventory_id')
    op.drop_column('products', 'status')
    op.drop_column('products', 'description')
    op.drop_column('products', 'renewal')
    op.drop_column('products', 'type')
    op.drop_column('products', 'title')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('renewal', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.alter_column('listings', 'inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('listings', 'id')
    op.add_column('channels', sa.Column('shop_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('shop_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
