"""empty message

Revision ID: 2b1747fcac2a
Revises: 16635d5168c3
Create Date: 2019-06-28 14:55:44.708144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1747fcac2a'
down_revision = '16635d5168c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_title_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_title_key', 'products', ['title'])
    # ### end Alembic commands ###
