"""empty message

Revision ID: 2f45511419cd
Revises: ac22e7c99277
Create Date: 2019-07-03 20:20:18.783033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f45511419cd'
down_revision = 'ac22e7c99277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels_etsy', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'channels_etsy', 'channels', ['channel_id'], ['id'])
    op.add_column('listings_etsy', sa.Column('listing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listings_etsy', 'listings', ['listing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings_etsy', type_='foreignkey')
    op.drop_column('listings_etsy', 'listing_id')
    op.drop_constraint(None, 'channels_etsy', type_='foreignkey')
    op.drop_column('channels_etsy', 'channel_id')
    # ### end Alembic commands ###
