"""empty message

Revision ID: 36b6e0162687
Revises: 8e43835e1273
Create Date: 2019-07-02 22:17:37.927526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b6e0162687'
down_revision = '8e43835e1273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'price')
    # ### end Alembic commands ###
