"""empty message

Revision ID: 38ccbac51f78
Revises: c1ad07894323
Create Date: 2019-07-29 19:10:14.639545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ccbac51f78'
down_revision = 'c1ad07894323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('merchants', 'first_name')
    op.drop_column('merchants', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('merchants', 'name')
    # ### end Alembic commands ###
