"""empty message

Revision ID: 39a4b49d825c
Revises: 88e37caec3cd
Create Date: 2019-06-27 18:57:35.627281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a4b49d825c'
down_revision = '88e37caec3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
