"""empty message

Revision ID: 48f1693b9933
Revises: 893782873042
Create Date: 2019-07-04 20:30:42.958206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f1693b9933'
down_revision = '893782873042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories_when_sold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventories', sa.Column('when_sold_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventories', 'inventories_when_sold', ['when_sold_id'], ['id'])
    op.drop_column('inventories', 'when_sold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('when_sold', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.drop_column('inventories', 'when_sold_id')
    op.drop_table('inventories_when_sold')
    # ### end Alembic commands ###
