"""empty message

Revision ID: 493b340439dc
Revises: e6fc4c6d4580
Create Date: 2019-07-16 16:24:46.602683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '493b340439dc'
down_revision = 'e6fc4c6d4580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventories_when_sold_id_fkey', 'inventories', type_='foreignkey')
    op.drop_table('inventories_when_sold')
    op.drop_column('inventories', 'when_sold_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('when_sold_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('inventories_when_sold_id_fkey', 'inventories', 'inventories_when_sold', ['when_sold_id'], ['id'], ondelete='CASCADE')
    op.create_table('inventories_when_sold',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='inventories_when_sold_pkey')
    )
    # ### end Alembic commands ###
