"""empty message

Revision ID: 4b20e46a6ea5
Revises: 4ecb985af702
Create Date: 2019-07-04 16:09:33.123213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b20e46a6ea5'
down_revision = '4ecb985af702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('_uid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', '_uid')
    # ### end Alembic commands ###
