"""empty message

Revision ID: 4ecd8bf5e6d2
Revises: db93216ca178
Create Date: 2019-07-15 14:53:31.460266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecd8bf5e6d2'
down_revision = 'db93216ca178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menus_account_id_fkey', 'menus', type_='foreignkey')
    op.drop_constraint('menus_platform_id_fkey', 'menus', type_='foreignkey')
    op.create_foreign_key(None, 'menus', 'platforms', ['platform_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'menus', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.create_foreign_key('menus_platform_id_fkey', 'menus', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key('menus_account_id_fkey', 'menus', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
