"""empty message

Revision ID: 55b6371f13dd
Revises: ddbdd14eedc2
Create Date: 2019-07-15 13:29:06.303147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b6371f13dd'
down_revision = 'ddbdd14eedc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('menus', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'title')
    op.drop_column('menus', 'is_active')
    # ### end Alembic commands ###
