"""empty message

Revision ID: 5a39fc3d763c
Revises: 3dac8e345228
Create Date: 2019-07-29 15:06:24.178377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a39fc3d763c'
down_revision = '3dac8e345228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'caption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
