"""empty message

Revision ID: 6bc444b2255a
Revises: a11165407d0e
Create Date: 2019-07-15 12:26:27.481369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bc444b2255a'
down_revision = 'a11165407d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('listings_channel_id_fkey', 'listings', type_='foreignkey')
    op.drop_table('channels')
    op.add_column('listings', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listings', 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
    op.drop_column('listings', 'channel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key('listings_channel_id_fkey', 'listings', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('listings', 'menu_id')
    op.create_table('channels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='channels_account_id_fkey'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name='channels_platform_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='channels_pkey')
    )
    op.drop_table('menus')
    # ### end Alembic commands ###
