"""empty message

Revision ID: 72f45c0f1fb1
Revises: 09ed7318a803
Create Date: 2019-07-04 16:51:51.962521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f45c0f1fb1'
down_revision = '09ed7318a803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('_sku', sa.String(length=255), nullable=True))
    op.drop_column('inventories', 'sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('sku', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('inventories', '_sku')
    # ### end Alembic commands ###
