"""empty message

Revision ID: 798b2d6fb34f
Revises: a88ccdb5527f
Create Date: 2019-07-02 22:38:21.483619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798b2d6fb34f'
down_revision = 'a88ccdb5527f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'is_active')
    # ### end Alembic commands ###
