"""empty message

Revision ID: 8580ff9ee573
Revises: 798b2d6fb34f
Create Date: 2019-07-03 11:07:58.229144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8580ff9ee573'
down_revision = '798b2d6fb34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'slug')
    # ### end Alembic commands ###
