"""empty message

Revision ID: 893782873042
Revises: 941d98241bae
Create Date: 2019-07-04 20:20:05.017809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893782873042'
down_revision = '941d98241bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'incoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('incoming', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
