"""empty message

Revision ID: 8e43835e1273
Revises: c472a3d2f962
Create Date: 2019-07-02 14:47:55.353208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e43835e1273'
down_revision = 'c472a3d2f962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.String(length=30), nullable=True))
    op.add_column('products', sa.Column('unique_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unique_id')
    op.drop_column('products', 'status')
    # ### end Alembic commands ###
