"""empty message

Revision ID: 941d98241bae
Revises: 72f45c0f1fb1
Create Date: 2019-07-04 16:53:28.806060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941d98241bae'
down_revision = '72f45c0f1fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('sku', sa.String(length=255), nullable=True))
    op.drop_column('inventories', '_sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('_sku', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('inventories', 'sku')
    # ### end Alembic commands ###
