"""empty message

Revision ID: a11165407d0e
Revises: a7fc7bc45052
Create Date: 2019-07-15 12:06:17.546652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a11165407d0e'
down_revision = 'a7fc7bc45052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels_etsy')
    op.drop_table('products_etsy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_etsy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('renewal', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('who_made_it', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('what_is_it', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('when_was_it_made', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('materials', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='products_etsy_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='products_etsy_pkey')
    )
    op.create_table('channels_etsy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oauth_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('oauth_token_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('shop_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('shop_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='channels_etsy_channel_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='channels_etsy_pkey')
    )
    # ### end Alembic commands ###
