"""empty message

Revision ID: a7fc7bc45052
Revises: c9271606a3dd
Create Date: 2019-07-15 11:56:10.046472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7fc7bc45052'
down_revision = 'c9271606a3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings_etsy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings_etsy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listing_etsy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name='listings_etsy_listing_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='listings_etsy_pkey')
    )
    # ### end Alembic commands ###
