"""empty message

Revision ID: a88ccdb5527f
Revises: 36b6e0162687
Create Date: 2019-07-02 22:33:07.946843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88ccdb5527f'
down_revision = '36b6e0162687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('available', sa.Integer(), nullable=True))
    op.drop_column('inventories', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inventories', 'available')
    # ### end Alembic commands ###
