"""empty message

Revision ID: c1ad07894323
Revises: f541a66d08b5
Create Date: 2019-07-29 16:56:23.899069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ad07894323'
down_revision = 'f541a66d08b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('apartment', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'website')
    op.drop_column('merchants', 'apartment')
    # ### end Alembic commands ###
