"""empty message

Revision ID: c472a3d2f962
Revises: cde092b27c83
Create Date: 2019-07-01 22:17:16.049080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c472a3d2f962'
down_revision = 'cde092b27c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('shop_id', sa.String(length=255), nullable=True))
    op.add_column('channels', sa.Column('shop_name', sa.String(length=255), nullable=True))
    op.add_column('channels', sa.Column('user_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'user_id')
    op.drop_column('channels', 'shop_name')
    op.drop_column('channels', 'shop_id')
    # ### end Alembic commands ###
