"""empty message

Revision ID: c9271606a3dd
Revises: d8ce39c563c2
Create Date: 2019-07-09 15:13:40.122397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9271606a3dd'
down_revision = 'd8ce39c563c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_etsy', sa.Column('materials', sa.Text(), nullable=True))
    op.add_column('products_etsy', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('products_etsy', sa.Column('what_is_it', sa.String(length=30), nullable=True))
    op.add_column('products_etsy', sa.Column('when_was_it_made', sa.String(length=30), nullable=True))
    op.add_column('products_etsy', sa.Column('who_made_it', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_etsy', 'who_made_it')
    op.drop_column('products_etsy', 'when_was_it_made')
    op.drop_column('products_etsy', 'what_is_it')
    op.drop_column('products_etsy', 'tags')
    op.drop_column('products_etsy', 'materials')
    # ### end Alembic commands ###
