"""empty message

Revision ID: ca87d149d6b0
Revises: 38ccbac51f78
Create Date: 2019-07-29 19:13:49.450602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca87d149d6b0'
down_revision = '38ccbac51f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('zipcode', sa.String(length=255), nullable=True))
    op.drop_column('merchants', 'zip_code')
    op.drop_column('merchants', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('zip_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('merchants', 'zipcode')
    op.drop_column('merchants', 'phone')
    # ### end Alembic commands ###
