"""empty message

Revision ID: d5f12c9d7a7c
Revises: 5a39fc3d763c
Create Date: 2019-07-29 15:06:41.688529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f12c9d7a7c'
down_revision = '5a39fc3d763c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
