"""empty message

Revision ID: d8ce39c563c2
Revises: aba3817b4f39
Create Date: 2019-07-09 14:57:38.446813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ce39c563c2'
down_revision = 'aba3817b4f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_etsy', sa.Column('section', sa.String(length=255), nullable=True))
    op.drop_column('products_etsy', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_etsy', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('products_etsy', 'section')
    # ### end Alembic commands ###
