"""empty message

Revision ID: ddbdd14eedc2
Revises: 6bc444b2255a
Create Date: 2019-07-15 12:52:08.127238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbdd14eedc2'
down_revision = '6bc444b2255a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventories', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.drop_constraint('inventories_product_id_fkey', 'inventories', type_='foreignkey')
    op.create_foreign_key(None, 'inventories', 'variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('inventories', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.create_foreign_key('inventories_product_id_fkey', 'inventories', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('inventories', 'variant_id')
    op.drop_table('variants')
    # ### end Alembic commands ###
