"""empty message

Revision ID: e5ebad9c7b2c
Revises: d5f12c9d7a7c
Create Date: 2019-07-29 15:58:53.387416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ebad9c7b2c'
down_revision = 'd5f12c9d7a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('county', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('phonenumber', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('zipcode', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'zipcode')
    op.drop_column('merchants', 'phonenumber')
    op.drop_column('merchants', 'last_name')
    op.drop_column('merchants', 'first_name')
    op.drop_column('merchants', 'county')
    op.drop_column('merchants', 'country')
    op.drop_column('merchants', 'city')
    # ### end Alembic commands ###
