"""empty message

Revision ID: e6fc4c6d4580
Revises: 4ecd8bf5e6d2
Create Date: 2019-07-16 13:39:57.079869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6fc4c6d4580'
down_revision = '4ecd8bf5e6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menus_platform_id_fkey', 'menus', type_='foreignkey')
    op.drop_table('platforms')
    op.drop_column('menus', 'platform_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('menus_platform_id_fkey', 'menus', 'platforms', ['platform_id'], ['id'], ondelete='CASCADE')
    op.create_table('platforms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='platforms_pkey'),
    sa.UniqueConstraint('name', name='platforms_name_key')
    )
    # ### end Alembic commands ###
