"""empty message

Revision ID: ea62566e5217
Revises: 2b1747fcac2a
Create Date: 2019-06-28 15:53:37.029361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea62566e5217'
down_revision = '2b1747fcac2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'platforms', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platforms', type_='unique')
    # ### end Alembic commands ###
