"""empty message

Revision ID: f0a409fc8596
Revises: 1ec048f23b1e
Create Date: 2019-07-04 23:53:41.299135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a409fc8596'
down_revision = '1ec048f23b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listings_channel_id_fkey', 'listings', type_='foreignkey')
    op.drop_constraint('listings_inventory_id_fkey', 'listings', type_='foreignkey')
    op.create_foreign_key(None, 'listings', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'listings', 'inventories', ['inventory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key('listings_inventory_id_fkey', 'listings', 'inventories', ['inventory_id'], ['id'])
    op.create_foreign_key('listings_channel_id_fkey', 'listings', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###
