"""empty message

Revision ID: f541a66d08b5
Revises: e5ebad9c7b2c
Create Date: 2019-07-29 16:10:14.181636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f541a66d08b5'
down_revision = 'e5ebad9c7b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('zip_code', sa.String(length=255), nullable=True))
    op.drop_column('merchants', 'phonenumber')
    op.drop_column('merchants', 'zipcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('zipcode', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('phonenumber', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('merchants', 'zip_code')
    op.drop_column('merchants', 'phone_number')
    # ### end Alembic commands ###
