import sys
import logging
import copy
from urllib.parse import urljoin
from io import BufferedReader

import requests


class Netlify:

    def __init__(
        self, 
        access_token: str, 
        scheme: str='https', 
        host: str='api.netlify.com', 
        version: str='/api/v1/'
    ):
        """The primary Netlify class .

            :param access_token: Personal access token generated by Netlify.
            :param scheme: Scheme of Netlify's API url.
            :param host: Host of Netlify's API url.
            :param version: Version of Netlify's API url.
        """
        self.access_token = access_token
        self.scheme = scheme
        self.host = host
        self.version = version
        self.url = f'{scheme}://{host}{version}'
        self.headers = {'Authorization': f'Bearer {access_token}'}

    def create_site(self, name: str) -> dict:
        """Create a site in Netlify.

            :param name: Name of site.
        """
        url = urljoin(self.url, 'sites')
        data = {'name': name}
        response = requests.post(url, data=data, headers=self.headers)
        site = response.json()

        return site

    def get_sites(self) -> list:
        """Get list of sites in Netlify."""
        url = urljoin(self.url, 'sites')
        response = requests.get(url, headers=self.headers)
        sites = response.json()

        return sites

    def get_site_id(self, name: str) -> str:
        """Get the ID of a site by its name.

            :param name: Name of site.
        """
        site_id = None
        sites = self.get_sites()
        for site in sites:
            if site['name'] == name:
                site_id = site['id']
                break

        if not site_id:
            logging.warning(f"Site '{name}' not found.")

        return site_id

    def deploy_site(
        self,
        site_id: str,
        file_digest: dict=None,
        zip_file: BufferedReader=None
    ) -> dict:
        """Deploy new or updated version of website.

        Netlify supports two ways of doing deploys:

        1. Sending a digest of all files in your deploy and then uploading \t
            any files Netlify doesn't already have on its storage servers.

        2. Sending a zipped website and letting Netlify unzip and deploy.

        The former is the recommended approach by Netlify.

            :param site_id: Site ID of a site.
            :param file_digest: Digest of file paths and SHA1 of file paths.
            :param zip_file: Content of zip file.
        """
        headers = copy.deepcopy(self.headers)
        url = urljoin(self.url, 'sites')
        url = f'{url}/{site_id}/deploys'

        if zip_file or file_digest:
            if zip_file:
                headers['Content-Type'] = 'application/zip'
                data = zip_file
            else:
                data = file_digest
        else:
            sys.exit('You must supply a zip file or a file digest')

        response = requests.post(url, headers=headers, data=data)
        status = response.json()

        return status
