import logging
from urllib.parse import urljoin
from dataclasses import dataclass, field
from typing import Dict

import requests


class Netlify:

    def __init__(
        self, 
        access_token: str, 
        scheme: str='https', 
        host: str='api.netlify.com', 
        version: str='/api/v1/'
    ):
        """The primary Netlify class.

            :param access_token: Personal access token generated by Netlify.
            :param scheme: Scheme of API url.
            :param host: Host of API url.
            :param version: Version of API url.
        """
        self.access_token = access_token
        self.scheme = scheme
        self.host = host
        self.version = version
        self.url = f'{scheme}://{host}{version}'
        self.headers = {'Authorization': f'Bearer {access_token}'}
        self.URL_SITES = urljoin(self.url, 'sites')

    def create_site(self, name: str):
        """Create site in Netlify.

            :param name: Name of site.
        """
        data = {'name': name}
        response = requests.post(
            self.URL_SITES, data=data, headers=self.headers
        )
        return response.json()

    def get_sites(self):
        response = requests.get(self.URL_SITES, headers=self.headers)
        import json
        logging.info(json.dumps(response.json(), indent=4, sort_keys=True))
        return response.json()

    def deploy_via_zip_file(self):
        return 0
