# Generated by Django 3.0.1 on 2020-02-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200202_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pxdcast',
        ),
    ]
