# Generated by Django 2.2.2 on 2019-06-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netprechaun', '0002_reward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reward',
            new_name='Referral',
        ),
    ]
