# Generated by Django 3.0.1 on 2020-01-06 17:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('job', models.CharField(max_length=254)),
                ('website', models.URLField()),
                ('address', models.CharField(max_length=254)),
                ('birthday', models.DateField()),
                ('company', models.CharField(max_length=254)),
                ('agent', models.CharField(max_length=254)),
                ('background', models.TextField()),
            ],
            options={
                'db_table': 'sidefone_contacts',
            },
        ),
    ]
