# Generated by Django 3.0.1 on 2020-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('img', models.URLField()),
                ('feed', models.URLField()),
                ('website', models.URLField()),
                ('apple_podcasts_id', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'pxdcast_podcasts',
            },
        ),
    ]
