name: deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Vercel Action
    - uses: actions/checkout@v2
    - uses: amondnet/vercel-action@v20
      with:
        github-comment: false
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
        working-directory: ./
        alias-domains: |
          podplayer.vercel.app
